
volumes:
  database-data:
    name: ${VOLUME_DATABASE_NAME}
    external: true

networks:
  internal:
    name: ${NETWORK_NAME}
    external: true

services:

  database:
    container_name: ${CONTAINER_NAME}
    build: .
    pull_policy: build
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_AUTO_UPGRADE=${MARIADB_AUTO_UPGRADE}
    volumes:
      - database-data:/var/lib/mysql
      #- ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      #- './my.cnf:/etc/mysql/my.cnf'
    networks:
      - internal

#    healthcheck:
#      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
#      interval: 10s
#      timeout: 15s
#      retries: 5