version: '3.7'

volumes:
  database-data:
    name: ${VOLUME_DATABASE_NAME}
    external: true

networks:
  internal:
    name: ${NETWORK_NAME}
    external: true

services:

  database:
    #image: mariadb:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - database-data:/var/lib/mysql
      #- ./etc/mysql/mariadb.conf.d/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      #- ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - internal
