version: '3.7'

volumes:
  database-data:
    name: ${VOLUME_DATABASE_NAME}

networks:
  internal:
    name: ${NETWORK_NAME}
    external: true

services:

  database_data:
    image: mariadb
    container_name: ${CONTAINER_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=3306
      - PMA_HOST=mysql
    volumes:
      - database-data:/var/lib/mysql
#    networks:
#      - internal


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
#      PMA_HOST: db
#      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
#    networks:
#      - internal
    ports:
      - 8087:80
