
volumes:
  database-data:
    name: ${VOLUME_DATABASE_NAME}
    external: true

networks:
  internal:
    name: ${NETWORK_NAME}
    external: true

services:

  database:
    image: mariadb:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - internal

    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 15s
      retries: 5